name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'index.html'
      - 'style.css'
      - 'script.js'
      - 'sw.js'
      - 'manifest.json'
      - '.nojekyll'
      - 'favicon.png'
      - 'icons/*'
      - '.github/workflows/deploy.yml'

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy para gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true
